name: jeevaniapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0  # For modern fonts
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.0

  mongo_dart: ^0.9.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.3.1
  location: ^6.0.2
  shimmer: ^3.0.0
  geocoding: ^3.0.0  # Add this
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png.jpeg
    - assets/tomato.jpg
    - assets/carrot.jpg
    - assets/potato.jpg


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png.jpeg"
